import com.percy.library.dao.BookDAO;
import com.percy.library.model.Book;

/**
 * Tests the BookDAO database operations.
 */
public class BookDAOTest {

    public static void main(String[] args) {

        // Create a BookDAO object.
        BookDAO bookDAO = new BookDAO();

        // Create a new Book object.
        Book newBook = new Book(
                0,
                "Java: The Complete Reference",
                "Herbert Schildt",
                "9781260440232",
                "Programming",
                2019,
                true
        );

        // Add the book to the database.
        int generatedId = bookDAO.addBook(newBook);

        // Display the ID generated by MySQL.
        System.out.println("New book ID: " + generatedId);

        // Retrieve the newly added book.
        Book savedBook = bookDAO.getBookById(generatedId);

        // Display the saved book.
        System.out.println("Saved book:");
        System.out.println(savedBook);
    }
}